### PR TITLE
prevent using find if there is no checking if id was wrong

### PR DESCRIPTION
**Pull request by intanirnanda5796**
hi, @oriene2021 . i just pull request about prevent using find if there is no checking id. just using findOrFail instead. if you want merge this pull request, don't forget to add label "hacktoberfest-accepted" . thank you

### CODE REVIEW

**Comment by oriene2021** [comment]
Thx for PR

**Comment by intanirnanda5796** [comment]
bug? what bug is it?

**Comment by oriene2021** [comment]
Don't worry, it's been fixed by @abdullah2205

**Comment by intanirnanda5796** [comment]
> Don't worry, it's been fixed by @abdullah2205

hmm ok. because i check before push, there is no problem when update and delete it work normally

**Pull request merged**
